version: 0.0
os: linux
files:
  - source: /deploy-scripts/frontend_deploy.sh
    destination: /home/ubuntu/deploy-scripts/frontend_deploy.sh
hooks:
  AfterInstall:
    - location: /home/ubuntu/deploy-scripts/frontend_deploy.sh
      timeout: 300
