version: 0.2

env:
  variables:
    ENVIRONMENT: ${ENVIRONMENT}

phases:
  pre_build:
    commands:
      - echo Logging in to Docker registry...
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Fetching Git commit hash...
      - GIT_COMMIT_HASH=$(git rev-parse HEAD)
      - echo Building Docker image...
      - echo $IMAGE_REPO_NAME:$GIT_COMMIT_HASH
      - docker build -t ${IMAGE_REPO_NAME}:${GIT_COMMIT_HASH} .
      
      # Define the image URI with commit hash
      - IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$GIT_COMMIT_HASH"
      - IMAGE_URI=$(echo ${IMAGE_URI} | tr -d '[:space:]')
      
      # Tag the image with 'latest'
      - docker tag ${IMAGE_REPO_NAME}:${GIT_COMMIT_HASH} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - echo "Pushing image with URI: ${IMAGE_URI}"
      # Push both the commit hash tag and the 'latest' tag
      - docker push ${IMAGE_URI}
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

artifacts:
  files:
    - '**/*'
